# render.yaml

services:
  - type: web
    name: justchill
    env: static
    buildCommand: echo "No build required for static site"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    headers:
      - path: /*
          Cache-Control: no-cache, no-store, must-revalidate
          Service-Worker-Allowed: /
      - path: /sw.js
          Cache-Control: no-cache, no-store, must-revalidate
          Service-Worker-Allowed: /
