# render.yaml

services:
  - type: web
    name: justchill
    env: static
    buildCommand: echo "No build required for static site"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
